In [42]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import statsmodels.formula.api as smf

house=pd.read_csv(r"house.csv")

In [43]:
house.head()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_basement,yr_built
0,7129300520,221900.0,3,1.00,1180,5650,1.0,0,0,3,0,1955
1,6414100192,538000.0,3,2.25,2570,7242,2.0,0,0,3,400,1951
2,5631500400,180000.0,2,1.00,770,10000,1.0,0,0,3,0,1933
3,2487200875,604000.0,4,3.00,1960,5000,1.0,0,0,5,910,1965
4,1954400510,510000.0,3,2.00,1680,8080,1.0,0,0,3,0,1987

In [44]:
house_model=shows.drop(['id'],axis=1)
house_model.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_basement,yr_built
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,0,1955
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,400,1951
2,180000.0,2,1.00,770,10000,1.0,0,0,3,0,1933
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,910,1965
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,0,1987

In [45]:
y=house_model[['price']]
x=house_model.drop(['price'],axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [46]:
X2 = sm.add_constant(x_train) #this ensures that it adds a constant line to your model
est = sm.OLS(y_train, X2)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.602
Model:                            OLS   Adj. R-squared:                  0.602
Method:                 Least Squares   F-statistic:                     2614.
Date:                Wed, 27 Jan 2021   Prob (F-statistic):               0.00
Time:                        21:51:32   Log-Likelihood:            -2.3824e+05
No. Observations:               17290   AIC:                         4.765e+05
Df Residuals:                   17279   BIC:                         4.766e+05
Df Model:                          10
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const          5.583e+06   1.57e+05     35.639      0.000    5.28e+06    5.89e+06
bedrooms      -5.481e+04   2392.533    -22.910      0.000   -5.95e+04   -5.01e+04
bathrooms      6.286e+04   4148.184     15.153      0.000    5.47e+04     7.1e+04
sqft_living     284.3604      3.426     83.008      0.000     277.646     291.075
sqft_lot         -0.3189      0.044     -7.275      0.000      -0.405      -0.233
floors         4.323e+04   4471.518      9.669      0.000    3.45e+04     5.2e+04
waterfront     5.708e+05   2.18e+04     26.198      0.000    5.28e+05    6.14e+05
view           6.015e+04   2695.569     22.316      0.000    5.49e+04    6.54e+04
condition      1.556e+04   2985.418      5.214      0.000    9712.990    2.14e+04
sqft_basement   -40.5808      5.295     -7.663      0.000     -50.960     -30.201
yr_built      -2893.4563     79.502    -36.395      0.000   -3049.288   -2737.625
==============================================================================
Omnibus:                    10279.443   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           349002.001
Skew:                           2.296   Prob(JB):                         0.00
Kurtosis:                      24.526   Cond. No.                     3.90e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.9e+06. This might indicate that there are
strong multicollinearity or other numerical problems.